### ISSUE TITLE
qap mac下无法启动工程

### ISSUE THREAD

**Issue by CrazyCui** [weex-nuke/discuss#20]
node版本10.13.0 / 8.13.0 qap-cli版本 3.1.15
qap init 新项目后 qap debug报错 报错信息
✖ ｢wdm｣: Hash: 93818f5a85d67ad8a82f
Version: webpack 4.26.1
Time: 1372ms
Built at: 2018-11-26 11:04:03
   Asset     Size  Chunks  Chunk Names
index.js  525 KiB   index  index
Entrypoint index = index.js
[0] multi /Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/webpackHotDevClient.js /Users/cuibolun/.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/patch.js ./pages/index/index 52 bytes {index} [built]
[../../../../.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/webpackHotDevClient.js] /Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/webpackHotDevClient.js 1.99 KiB {index} [built] [failed] [1 error]
[../../../../.fie/node_modules/_global@4.3.2@global/window.js] /Users/cuibolun/.fie/node_modules/_global@4.3.2@global/window.js 232 bytes {index} [built]
[../../../../.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/lib/patch.dev.js] /Users/cuibolun/.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/lib/patch.dev.js 5.5 KiB {index} [built]
[../../../../.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/lib/patch.js] /Users/cuibolun/.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/lib/patch.js 209 bytes {index} [built]
[../../../../.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/patch.js] /Users/cuibolun/.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/patch.js 40 bytes {index} [built]
[../../../../.fie/node_modules/_react-deep-force-update@1.1.2@react-deep-force-update/lib/index.js] /Users/cuibolun/.fie/node_modules/_react-deep-force-update@1.1.2@react-deep-force-update/lib/index.js 2.4 KiB {index} [built]
[../../../../.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/bindAutoBindMethods.js] /Users/cuibolun/.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/bindAutoBindMethods.js 2.96 KiB {index} [built]
[../../../../.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/createClassProxy.js] /Users/cuibolun/.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/createClassProxy.js 7.9 KiB {index} [built]
[../../../../.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/createPrototypeProxy.js] /Users/cuibolun/.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/createPrototypeProxy.js 5.58 KiB {index} [built]
[../../../../.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/index.js] /Users/cuibolun/.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/index.js 1.04 KiB {index} [built]
[../../../../.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/supportsProtoAssignment.js] /Users/cuibolun/.fie/node_modules/_react-proxy@1.1.8@react-proxy/modules/supportsProtoAssignment.js 275 bytes {index} [built]
[../../../../.fie/node_modules/_webpack@4.26.1@webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {index} [built]
[./pages/index/index.jsx] 1.99 KiB {index} [built] [failed] [1 error]
[rax] external "rax" 42 bytes {index} [built]
    + 147 hidden modules

ERROR in /Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/webpackHotDevClient.js
Module build failed (from /Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/module-hot-accept.js):
Error: Cannot find module 'loader-utils'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/module-hot-accept.js:3:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/cuibolun/.fie/node_modules/_webpack@4.26.1@webpack/lib/NormalModule.js:265:3)
    at NormalModule.build (/Users/cuibolun/.fie/node_modules/_webpack@4.26.1@webpack/lib/NormalModule.js:412:15)
    at Compilation.buildModule (/Users/cuibolun/.fie/node_modules/_webpack@4.26.1@webpack/lib/Compilation.js:633:10)
 @ multi /Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/webpackHotDevClient.js /Users/cuibolun/.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/patch.js ./pages/index/index index[0]

ERROR in ./pages/index/index.jsx
Module build failed (from /Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/module-hot-accept.js):
Error: Cannot find module 'loader-utils'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/module-hot-accept.js:3:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/cuibolun/.fie/node_modules/_loader-runner@2.3.1@loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/cuibolun/.fie/node_modules/_webpack@4.26.1@webpack/lib/NormalModule.js:265:3)
    at NormalModule.build (/Users/cuibolun/.fie/node_modules/_webpack@4.26.1@webpack/lib/NormalModule.js:412:15)
    at Compilation.buildModule (/Users/cuibolun/.fie/node_modules/_webpack@4.26.1@webpack/lib/Compilation.js:633:10)
 @ multi /Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/hot-dev-utils/webpackHotDevClient.js /Users/cuibolun/.fie/node_modules/_rax-hot-loader@0.6.5@rax-hot-loader/patch.js ./pages/index/index index[2]
Child html-webpack-plugin for "debugger.html":
            Asset     Size  Chunks  Chunk Names
    debugger.html  589 KiB       0
    Entrypoint undefined = debugger.html
    [../../../../.fie/node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!../../../../.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/tpl/new/debugger.html] /Users/cuibolun/.fie/node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!/Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/tpl/new/debugger.html 31.8 KiB {0} [built]
    [../../../../.fie/node_modules/_lodash@4.17.11@lodash/lodash.js] /Users/cuibolun/.fie/node_modules/_lodash@4.17.11@lodash/lodash.js 527 KiB {0} [built]
    [../../../../.fie/node_modules/_webpack@4.26.1@webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [../../../../.fie/node_modules/_webpack@4.26.1@webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
Child html-webpack-plugin for "download.html":
            Asset     Size  Chunks  Chunk Names
    download.html  564 KiB       0
    Entrypoint undefined = download.html
    [../../../../.fie/node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!../../../../.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/tpl/new/download.html] /Users/cuibolun/.fie/node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!/Users/cuibolun/.fie/node_modules/_fie-toolkit-nuke@0.9.5@fie-toolkit-nuke/lib/tpl/new/download.html 6.04 KiB {0} [built]
    [../../../../.fie/node_modules/_lodash@4.17.11@lodash/lodash.js] /Users/cuibolun/.fie/node_modules/_lodash@4.17.11@lodash/lodash.js 527 KiB {0} [built]
    [../../../../.fie/node_modules/_webpack@4.26.1@webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [../../../../.fie/node_modules/_webpack@4.26.1@webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
进入H5容器

**Comment by CrazyCui** [comment]
node 版本v8.13.0
mac系统版本 10.14.1 (18B75)

**Comment by fattydevelop** [comment]
三方依赖问题，更新最新版可以解决
